language: android

jdk:
- oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-19
    - android-21
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - install_ndk.sh
  # see https://github.com/travis-ci/travis-ci/issues/8874
  - yes | sdkmanager "platforms;android-27"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

script: ./gradlew checkstyle clean build

sudo: true
